spring:
  application:
    name: legendkim
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://localhost:3306/legenokim
    username: legeno
    password: legeno
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # ======================================
  # 임시 Security 계정 (개발용 - 배포 전 반드시 삭제)
  # ======================================
  security:
    user:
      name: admin01
      password: admin1234

file:
  upload-dir: uploads/lectures
